export const missions: any[] = [
  {
    id: 1,
    end_date: '2023-10-10',
    free_days: 1,
    id_user: null,
    is_active: false,
    is_for_me: null,
    name: 'Mission1',
    sell_days: null,
    share_mission: null,
    start_date: '2023-10-01',
    tjm: 1.00,
    company_id: 1,
    facturation_id: 1,
    facturation_type: null
  },
  {
    id: 2,
    end_date: '2023-10-19',
    free_days: 2,
    id_user: null,
    is_active: false,
    is_for_me: null,
    name: 'Mission2',
    sell_days: null,
    share_mission: null,
    start_date: '2023-10-02',
    tjm: 2.00,
    total_days: 2,
    company_id: 2,
    facturation_id: 2,
    facturation_type: null
  },
  {
    id: 3,
    end_date: '2023-10-24',
    free_days: 0,
    id_user: 4,
    is_active: false,
    is_for_me: true,
    name: 'Mission333',
    sell_days: true,
    share_mission: true,
    start_date: '2023-10-24',
    tjm: 0.00,
    total_days: 3,
    company_id: 3,
    facturation_id: 3,
    facturation_type: null
  },
  {
    id: 4,
    end_date: '2023-10-24',
    free_days: 0,
    id_user: 4,
    is_active: false,
    is_for_me: true,
    name: 'Mission4',
    sell_days: true,
    share_mission: true,
    start_date: '2023-10-24',
    tjm: 0.00,
    total_days: 4,
    company_id: 4,
    facturation_id: 4,
    facturation_type: null
  }
];
